Exception handler + DataSource.Conifg + Repaired Build
openschoolmanagement/calendar-task-project-service pull request #3
Opened 2018-05-31 19:29 UTC by neolytian

2018-06-02 06:53 UTC, thbonk requested changes

2018-06-02 06:53 UTC, thbonk commented on src/main/java/open/schoolmanagement/time/calendartaskprojectservice/config/DataSourceConfig.java
> +  }
(y)

2018-06-02 06:53 UTC, thbonk commented on src/main/java/open/schoolmanagement/time/calendartaskprojectservice/config/FlywayConfig.java
> +  @Autowired
Ich weiß nicht, ob man diese Konfiguration braucht. Flyway läuft auch ohne die an.

2018-06-02 06:53 UTC, thbonk commented on src/main/java/open/schoolmanagement/time/calendartaskprojectservice/controller/calendar/CalendarController.java
> +        .build();
Testcode?

2018-06-02 06:53 UTC, thbonk commented on src/main/resources/db/migration/V1_SETUP_DATABASE.sql
> +CREATE DATABASE  IF NOT EXISTS OSM_CALENDAR ;
"IF NOT EXISTS" braucht man hier noch nicht.

2018-06-06 17:04 UTC, neolytian commented on src/main/java/open/schoolmanagement/time/calendartaskprojectservice/controller/calendar/CalendarController.java
> +        .build();
Upsy...

2018-06-06 17:07 UTC, neolytian commented
Changes Done! Can be approved

2018-06-06 17:14 UTC, thbonk approved these changes

2018-06-06 17:14 UTC, merged